
# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#

### Newt config file ###
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.4.1"

    steps:
      - checkout

      # - run:
      #     name: Install Carthage
      #     command: carthage bootstrap --no-use-binaries

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan --project "Newt/Newt.xcodeproj"
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Newt

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
